# Generated by Django 3.2.18 on 2023-04-06 10:59

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercises',
            options={'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ['-recent_workouts'], 'verbose_name_plural': 'Tracker'},
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='exercise_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.exercises'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercises',
            name='exercise_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='recent_workouts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='workouts.workouttemplate'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Template'), (1, 'Add to Tracker')], default=0),
        ),
    ]
