# Generated by Django 3.2.18 on 2023-04-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20230406_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=3),
        ),
    ]
