# Generated by Django 3.2.18 on 2023-04-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workouttemplate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplate',
            name='was_performed',
            field=models.BooleanField(default=False),
        ),
    ]
