# Generated by Django 3.2.18 on 2023-04-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_remove_workouttemplate_log_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplate',
            name='time_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
