# Generated by Django 3.2.18 on 2023-04-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_workouttemplate_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplate',
            name='template_name',
            field=models.CharField(max_length=50),
        ),
    ]
