# Generated by Django 3.2.18 on 2023-04-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_alter_workouttemplate_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplate',
            name='template_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
