# Generated by Django 3.2.18 on 2023-04-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_auto_20230420_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouttemplate',
            old_name='athlete_id',
            new_name='athlete_instance',
        ),
    ]
