# Generated by Django 3.2.18 on 2023-04-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_rename_athlete_id_workouttemplate_athlete_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplate',
            name='template_name',
            field=models.CharField(max_length=50),
        ),
    ]
