# Generated by Django 3.2.18 on 2023-09-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_alter_workouttemplate_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
