# Generated by Django 3.2.18 on 2023-09-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_alter_workoutlog_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
