# Generated by Django 3.2.18 on 2023-09-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0018_alter_workoutlog_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
